version: '3.2'

services:
  db:
    image: postgres:9.6
    restart: always
    ports:
      - 6432:5432
    volumes:
      - /tmp/sa-db-data:/var/lib/postgresql/data

  backend:
    build: .
    ports:
      - 8080:8080
    environment:
      - POSTGRES_HOST=db
    depends_on:
      - db